# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftuiKnowledge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftuiKnowledge
  pod 'SnapKit'
  pod 'Moya'
  pod 'QMUIKit'
  pod 'pop'
  # pod 'Spring'
  pod 'Kingfisher'
  pod 'YYKit'

  target 'SwiftuiKnowledgeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftuiKnowledgeUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end
